- name: Setup Android SDK
  run: |
    mkdir -p $HOME/android-sdk/cmdline-tools
    wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
    unzip -q sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
    mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
    export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
    yes | sdkmanager --licenses
    sdkmanager --sdk_root=$HOME/android-sdk \
      "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;25.1.8937393"
