name: Build Kivy APK with Buildozer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate assets
        run: |
          if [ ! -f assets/icon.png ]; then
            echo "⚠️ assets/icon.png missing—please add or generate placeholder"
            exit 1
          fi

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 python3-pip openjdk-11-jdk zip unzip \
            autoconf automake libtool pkg-config zlib1g-dev

      - name: Upgrade Buildozer & Cython
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Fix Autoconf macros & update configure.ac
        run: |
          if [ -f configure.ac ]; then
            autoupdate
            echo 'm4_pattern_allow([LT_SYS_SYMBOL_USCORE])' >> configure.ac
          fi

      - name: Setup Android SDK for Buildozer
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          ln -s $HOME/android-sdk/cmdline-tools/latest $HOME/android-sdk/tools
          yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses
          $HOME/android-sdk/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;25.1.8937393"

      - name: Link SDK into Buildozer path
        run: |
          rm -rf ~/.buildozer/android/platform/android-sdk
          mkdir -p ~/.buildozer/android/platform
          ln -s $HOME/android-sdk ~/.buildozer/android/platform/android-sdk

      - name: Export Android env vars
        run: |
          echo "ANDROIDNDK=$HOME/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROIDAPI=31"             >> $GITHUB_ENV
          echo "ANDROIDMINAPI=21"          >> $GITHUB_ENV

      - name: Build APK (verbose debug)
        run: |
          buildozer --verbose android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: parchisi-kingdoms-apk
          path: bin/*.apk
